### PR TITLE
1360. Codeforces Round #644 (Div. 3) [Haskell]

### PR DESCRIPTION
**Pull request by neltsu**
For fun, I solved this contest using Haskell.

### CODE REVIEW

**Comment by Vicfred** [comment]
This is really cool, this is the first haskell code in the repo and I hope we get more :D 

I'm gonna check the code and try to make some comments before I accept the PR just let me fully wake up :P

**Review by Vicfred — COMMENTED** [review]
please add more function signatures

**Comment by neltsu** [comment]
Unrelated question: wouldn't it be better for filenames to start with the contest name so that it is easier to find related solutions?

**Comment by Vicfred** [comment]
Yes, actually the problems from atcoder are named like that, let's change it for the codeforces too starting with these :D

**Comment by Vicfred** [comment]
btw @unihernandez22 just changed the name of the codeforces' files to the new naming convention :D

**Pull request merged**
